### ISSUE TITLE
not able to download any app....as i am beginner and i am doin an project on android malware detection so i need to download 11k apps....   plz tell me step by step procedure the problem i faced was when i started crawler it  gives output that 0 page crawled and all ,,,,and when to start downloader ?? plz tell me as soon as possible.....thanx in advance

### ISSUE THREAD

**Issue by abhishekpareek** [mssun/android-apps-crawler#5]

**Comment by mssun** [comment]
Can you describe your issue in detail? I guess the SCRAPE_RULES in settings should be updated for some markets.

**Comment by abhishekpareek** [comment]
i have started the crawler but it goes on ....it was running till one day then i stopped ,,,,and started downloader but there was output thread 1 asked to exit and till thread 20 asked to exit  ,,,,,,,,,so let me know where i am making mistake,,,,,nd explain step by step,,,,,it would be great pleasure for me.....thanx in advance,,,,,,awatiing for your reply... :)

**Comment by abhishekpareek** [comment]
please reply i am having problem in this

**Comment by mssun** [comment]
Because the webpage structure of these third party markets may change, you need to update the rules manually for specific webpage. I also also use some SQLite tool to check the scraped items in the database.

**Comment by abhishekpareek** [comment]
I dnt have idea about this... And I didn't get it.... Can u help me... I only  need to downlaod apps in a collection of 10 thousand so that I can complete my project on detecting and testing vulnerability  into them...... .. Plz describe how to start that and how can I use.... When to start downloader. Py when to start crawler. Sh and where to update the rules.... Thanx in advance

**Comment by abhishekpareek** [comment]
Please reply fast... Its urgent... Please I have to complete it till 27
