### ISSUE TITLE
Download Threads Stop Making Progress

### ISSUE THREAD

**Issue by jgarci40** [mssun/android-apps-crawler#6]
I am using your crawler to download apps from anzhi. After some time, I notice the download threads no longer make progress. For example, at a seemingly random point, the downloads stop continuing, although the threads still run. Is there a way that you can recommend detecting when this occurs and simply restart the downloads so that downloader.py can continue to make progress? Thank you for your time.

**Comment by mssun** [comment]
Hi, thanks for your interests. I met the same issue with you before. I couldn't find the main cause neither. I guess the server may shutdown/slow down the download rate. It should be better to implement a timeout and retry mechanism. My temporary solution is to stop and restart the downloader.

**Comment by lingfennan** [comment]
Hi, I am using your crawler to download apps. I tried to download from different app stores, but only anzhi.com seems working. For all the other app stores, I get error saying: 
[boto] ERROR: Caught exception reading instance data

Do you have any idea why this is happening? Is this some bug in boto or some other issues? Thanks!

**Comment by mssun** [comment]
Hi, let me have a try and give you feedback. I guess part of the reason is that the XPATH for the download urls is changed.

**Comment by lingfennan** [comment]
Thanks for the quick reply! I find anzhi.com has the same error as other app stores. boto may not be the cause. Maybe other app stores changed their APIs?

**Comment by mssun** [comment]
I can run anzhi.com successfully. If you see

```
2015-12-17 15:56:38 [scrapy] INFO: Catch an AppItem
2015-12-17 15:56:38 [scrapy] INFO: Inserting into database
```

This means that it works, and has captured an app.

**Comment by lingfennan** [comment]
Yes. anzhi.com works. But other app stores don't work any more, I have tested hiapk.com, appchina.com, appfun.cn.

**Comment by mssun** [comment]
I just push a commit which fixed hiapk.com. You can have a try.

**Comment by mssun** [comment]
I will then write a document about updating deprecated websites and adding new websites.

**Comment by lingfennan** [comment]
Awesome! Thank you! I also fixed the XPATH for appchina.com and have it working.
The XPATH that I am using for app china is:
//div[@class='download-button direct_download']/a/@href

**Comment by mssun** [comment]
I guess it is not so hard. You can send me pull requests (if you fix any XPATH or add new sites).
